---
title: "Expresíon diferencial"
author: "Carmen Gómez Valenzuela"
date: "Junio de 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Cargamos los counts e información del grupo de cada muestra

```{r, message=FALSE}
library(readr)

phenodata <- read_delim("phenodata.txt", "\t", escape_double = FALSE, trim_ws = TRUE)
table <- readRDS("circ_annotations.rds")

```

```{r}
#Conjunto de datos Hepatocellular-Normal
counts.hep <- table[,phenodata$File[phenodata$Group %in% c("normal","hepatocellular")]]
counts.hep <- counts.hep[ rowSums(counts.hep) >0,]
group.hep <- phenodata$Group[phenodata$Group %in% c("normal","hepatocellular")]

#Conjunto de datos Pancreatic-Normal
counts.panc <- table[,phenodata$File[phenodata$Group %in% c("normal","pancreatic")]]
counts.panc <- counts.panc[rowSums(counts.panc)>0,]
group.panc <- phenodata$Group[phenodata$Group %in% c("normal","pancreatic")]

#Conjunto de datos Colorectal-Normal
counts.col <- table[,phenodata$File[phenodata$Group %in% c("normal","colorectal")]]
counts.col <- counts.col[rowSums(counts.col) >0,]
group.col <- phenodata$Group[phenodata$Group %in% c("normal","colorectal")]
```

```{r}
library(DESeq2)
dds.col <- DESeqDataSetFromMatrix(countData = counts.col, colData =data.frame(group = as.factor(group.col)), design= ~ group )
dds.col <- estimateSizeFactors( dds.col )
idx <- rowSums(counts(dds.col,normalized=TRUE)>=10) >= 10
dds.col <- dds.col[idx,]
dds.col <- DESeq( dds.col ,minReplicatesForReplace=Inf)
res.col <- results( dds.col, cooksCutoff=FALSE, independentFiltering=FALSE)

```

```{r}
dds.hep <- DESeqDataSetFromMatrix(countData = counts.hep, colData =data.frame(group = as.factor(group.hep)), design= ~ group )
dds.hep <- estimateSizeFactors( dds.hep )
idx <- rowSums(counts(dds.hep,normalized=TRUE)>=15) >= 10
dds.hep <- dds.hep[idx,]
dds.hep <- DESeq( dds.hep ,minReplicatesForReplace=Inf)
res.hep <- results( dds.hep, cooksCutoff=FALSE, independentFiltering=FALSE)

```



```{r}
dds.panc <- DESeqDataSetFromMatrix(countData = counts.panc, colData =data.frame(group = as.factor(group.panc)), design= ~ group )
dds.panc <- estimateSizeFactors( dds.panc )
idx <- rowSums(counts(dds.panc,normalized=TRUE)>=15) >= 0.7*ncol(counts.panc)
dds.panc <- dds.panc[idx,]
dds.panc <- DESeq( dds.panc ,minReplicatesForReplace=Inf)
res.panc <- results( dds.panc, cooksCutoff=FALSE, independentFiltering=FALSE)

```
